### PR TITLE
Assignment2

### PR DESCRIPTION
**Pull request by nishusingh11**
Hey Vince, 
I have implemented assignment 2, kindly review it. 
outputs of each table are attached here.

Historical_batting_avg_output

Annual_batting_avg_output

Rolling_batting_avg

### CODE REVIEW

**Comment by nishusingh11** [comment]
Hey Vince,
Kindly review changes.

Tables output:

Historical_average

Annual_average

Rolling_average

**Comment by vdayes7** [comment]
Ok, good you followed the suggestion I made (over the phone) for putting the batter first in the third table and sorting on the game_id.  My new suggestions would be to sort by batter on third table so it starts with the same batter as the other two tables.  Also, maybe as an accuravy check you could give the total # of records/rows in each table Uness it takes too long)  The second table should have more than the first table and the third shoud have way more than the second.  I am having trouble downloading this branch into pycharms and running everything from there but that is my problem.  I will keep trying.

**Comment by vdayes7** [comment]
Ok, almost ran everything - put in manually the three commands that were missing from the Readme file and everything was going fine until the last one:

[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /Users/vdayes/.cache/pre-commit/patch1632525364.
[INFO] Initializing environment for git@github.com:Yelp/detect-secrets.
[INFO] Restored changes from /Users/vdayes/.cache/pre-commit/patch1632525364.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
expected return code: 0
stdout: (none)
stderr:
    git@github.com: Permission denied (publickey).
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.
    
Check the log at /Users/vdayes/.cache/pre-commit/pre-commit.log
(env) VSD:bda696 vdayes$ 

I will keep trying to figure this out.

**Comment by vdayes7** [comment]
There are things I want to mention that probably don't matter at all.  I am new at this so I don't know how things are supposed to be.

In the package download, it has the iris.data, iris.name, and homework1.py.  That may be ok, I just want to mention it.  And then really minor stuff that you probably don't need to change in the comments - misspelling of rolling - you have rolling.  And this is really minor - "batting average for every batter" sounds really weird to me.  "batting average for every player" is much better - especially since many players get in a game and don't get to bat so they are not batters.  Same thing in "Calculation of batting average for every batter annually" - "... every player annually" would sound better.  But again, those things may not matter at all.

**Pull request merged**
