### PR TITLE
Implementation of Assignment4

### PR DESCRIPTION
**Pull request by nishusingh11**
Hey Vince,
Kindly review my assignment 4. I have used flask to render html file. All the outputs are stored in plot in working directory. I have executed pre-commit, screenshot of passed dependencies and out are attached here.
output:
Homework4

Dependencies:

Dependencies

### CODE REVIEW

**Comment by vdayes7** [comment]
Ok, am still reviewing but here are some things you might consider:  
print(feature) (line 328) may be unnecessary - there is a column of unnecessary data for each feature.  We have already seen the data above (mostly) and there is a min & max at the bottom.  Also maybe the min & max should be labeled?  Then there are the square differences - weighted and unweighted that have 18 digits after the decimal point.  Can they be rounded off?   Ok, am going to look at plots now.

**Comment by vdayes7** [comment]
Is there a table with the features ranked in order of importance?  Isn't that the point of all this?  To find the good predictors.  Also should there be plots of mean of response with weighted differences?

**Comment by nishusingh11** [comment]
> Ok, am still reviewing but here are some things you might consider: print(feature) (line 328) may be unnecessary - there is a column of unnecessary data for each feature. We have already seen the data above (mostly) and there is a min & max at the bottom. Also maybe the min & max should be labeled? Then there are the square differences - weighted and unweighted that have 18 digits after the decimal point. Can they be rounded off? Ok, am going to look at plots now.

-print feature was for testing purpose, I will remove that statement.
-First min max is to calculate the bin range , second min max is calculating the low and high value of each bin.
-I will roundoff the square diff for both the tables.

**Comment by nishusingh11** [comment]
> Is there a table with the features ranked in order of importance? Isn't that the point of all this? To find the good predictors. Also should there be plots of mean of response with weighted differences?

yes, that make sense. I will sort the predictors list according to the importance.

**Comment by vdayes7** [comment]
Ok, changes made.  My fault, I did not have time to run other datasets through.

**Review by vdayes7 — APPROVED** [review]
Looks like all changes have been made.

**Comment by nishusingh11** [comment]
Hello Professor,
Kindly review this PR. I have addressed all the review comments mentioned by my code buddy.

**Pull request merged**
